candidates:
  - Trump
  - Biden
  - Republican
  - Democrat

doc_api:
  date_range: "01-Aug-2020 - 16-Oct-2020"  # UI format
  maxrecords: 250       # up to 250 per query
  keywords:
    - stock
  source_lang: ENG        # e.g., "ENG" (GDELT language codes)
  source_country:     # e.g., "US" (two-letter country code)
  domain_whitelist: []
